version: "3"
services:
  moduly.asterionrpg:
    build: .
    environment:
      PROJECT_ENVIRONMENT: "prod"
    volumes:
      - .docker/home:/home
      - .docker/root:/root
      - .docker/etc/caddy:/etc/caddy
      - ./www:/var/www
    expose:
      - "80"
    restart: "always"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
