# # docker pull jaroslavtyc/moduly.asterionrpg:latest && docker-compose build
version: "3"
services:
  moduly.asterionrpg:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=asterionrpg.loc"
      PROJECT_ENVIRONMENT: "dev"
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 idekey=PHPSTORM remote_log=/tmp/xdebug.log"
    volumes:
      - ./www:/var/www:delegated
      - ./.docker/etc/caddy:/etc/caddy:delegated
      - ./.docker/entrypoint.sh:/entrypoint.sh:delegated
    entrypoint:
      - sh
      - -c
      - set -x && docker-php-ext-enable xdebug && touch /tmp/xdebug.log && chmod 0777 /tmp/xdebug.log && /bin/bash /entrypoint.sh
    expose:
      - "80"
    restart: "no"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
