version: "3"
services:
  moduly.asterionrpg:
    environment:
      PROJECT_ENVIRONMENT: "prod"
    volumes:
      - .docker/home:/home
      - .docker/root:/root
      - .docker/etc/caddy:/etc/caddy
    ports:
      - "80:80"
      - "443:443"
    restart: "always"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
